### ISSUE TITLE
Error when returning false on a before.find hook

### ISSUE THREAD

**Issue by taromero** [yogiben/meteor-admin#134]
I'm writing some code on `before` hooks to implement abilities on my app, and on a certain scenario, I don't want `find` to retrieve any record.

To achieve this, I return `false`, which is the [documented way to do it](https://github.com/matb33/meteor-collection-hooks#user-content-additional-notes):

``` javascript
MyCollection.before.find = function(...) {
  if (condition) {
    return false
  }
  ...
}
```

That produces an error that seems to be caused by a lib used by `meteor-admin`:

> Exeption while invoking method 'pages_examsCountPages' TypeError: Object false has no method 'count'
    at Pages.__Pages.Pages.methods.CountPages (packages/alethes:pages/lib/pages.coffee:63:9)
        at [object Object].<anonymous> (packages/alethes:pages/lib/pages.coffee:194:17)
            at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
                at packages/ddp/livedata_server.js:648:1
                    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
                        at packages/ddp/livedata_server.js:647:1
                            at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
                                at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
                                    at packages/ddp/livedata_server.js:546:1

**Comment by taromero** [comment]
For now, as a workaround, I'm throwing exceptions instead of returning false, just in case someone is having the same issue.

**Comment by mpowaga** [comment]
`meteor-admin` assumes that `find` method returns a cursor which is the case for meteor collections. You would have to return an empty cursor in order to make it work.
