### ISSUE TITLE
OMG first bad meteor experience opening /admin

### ISSUE THREAD

**Issue by teddis** [yogiben/meteor-admin#195]
I just added the latest admin add-on to my Meteor simple todo project and got this:
Help!

I20150524-14:26:28.596(-4)? Exception while invoking method 'adminCheckAdmin' TypeError: Cannot read property 'length' of undefined
I20150524-14:26:28.597(-4)?     at [object Object].Meteor.methods.adminCheckAdmin (packages/yogiben:admin/lib/server/methods.coffee:76:82)
I20150524-14:26:28.597(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150524-14:26:28.597(-4)?     at packages/ddp/livedata_server.js:648:1
I20150524-14:26:28.597(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150524-14:26:28.598(-4)?     at packages/ddp/livedata_server.js:647:1
I20150524-14:26:28.598(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150524-14:26:28.598(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150524-14:26:28.598(-4)?     at packages/ddp/livedata_server.js:546:1

**Comment by waigani** [comment]
Looking at the code, adminCheckAdmin asserts the length of the user's email to be larger than 0. But if the user doesn't have an email, that would cause an error like the one you are seeing.

**Comment by johnflux** [comment]
I just hit this problem too.
