### ISSUE TITLE
ATCreateUserServer Error: failed [404] when sign up

### ISSUE THREAD

**Issue by leetschau** [yogiben/meteor-admin#199]
I cloned the repo, and start meteor server. The backend mongodb version is 3.0.3.
When connecting to http://localhost:3000/admin, it jumped to login page.
I clicked the sign up button, and input my email and password, the server print the following error messages:

```
=> App running at: http://localhost:3000/
I20150602-08:22:03.080(8)? Exception while invoking method 'ATCreateUserServer' Error: failed [404]
I20150602-08:22:03.081(8)?     at Object.Future.wait (/home/leo/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
I20150602-08:22:03.081(8)?     at packages/meteor/helpers.js:119:1
I20150602-08:22:03.081(8)?     at server/accounts.coffee:36:3
I20150602-08:22:03.082(8)?     at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:999:1)
I20150602-08:22:03.082(8)?     at createUser (packages/accounts-password/password_server.js:718:1)
I20150602-08:22:03.082(8)?     at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
I20150602-08:22:03.082(8)?     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts:core/lib/methods.js:105:1)
I20150602-08:22:03.082(8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150602-08:22:03.083(8)?     at packages/ddp/livedata_server.js:648:1
I20150602-08:22:03.083(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150602-08:22:03.083(8)?     - - - - -
I20150602-08:22:03.084(8)?     at Object.Future.wait (/home/leo/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150602-08:22:03.084(8)?     at Object.call (packages/meteor/helpers.js:119:1)
I20150602-08:22:03.084(8)?     at [object Object].Meteor.methods._cfs_getUrlInfo (packages/cfs:file/fsFile-server.js:186:1)
I20150602-08:22:03.085(8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150602-08:22:03.086(8)?     at packages/ddp/livedata_server.js:1530:1
I20150602-08:22:03.086(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150602-08:22:03.086(8)?     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
I20150602-08:22:03.086(8)?     at [object Object]._.extend.call (packages/ddp/livedata_server.js:1472:1)
I20150602-08:22:03.087(8)?     at EventEmitter.fsFileAttachData [as attachData] (packages/cfs:file/fsFile-common.js:81:1)
I20150602-08:22:03.087(8)?     at packages/meteor/helpers.js:118:1
I20150602-08:22:03.087(8)?     - - - - -
I20150602-08:22:03.087(8)?     at makeErrorByStatus (packages/http/httpcall_common.js:12:1)
I20150602-08:22:03.088(8)?     at Request._callback (packages/http/httpcall_server.js:109:1)
I20150602-08:22:03.088(8)?     at Request.self.callback (/home/leo/.meteor/packages/http/.1.1.0.43csqa++os+web.browser+web.cordova/npm/node_modules/request/request.js:344:22)
I20150602-08:22:03.088(8)?     at Request.emit (events.js:98:17)
I20150602-08:22:03.088(8)?     at Request.<anonymous> (/home/leo/.meteor/packages/http/.1.1.0.43csqa++os+web.browser+web.cordova/npm/node_modules/request/request.js:1239:14)
I20150602-08:22:03.089(8)?     at Request.emit (events.js:117:20)
I20150602-08:22:03.089(8)?     at IncomingMessage.<anonymous> (/home/leo/.meteor/packages/http/.1.1.0.43csqa++os+web.browser+web.cordova/npm/node_modules/request/request.js:1187:12)
I20150602-08:22:03.089(8)?     at IncomingMessage.emit (events.js:117:20)
I20150602-08:22:03.089(8)?     at _stream_readable.js:944:16
I20150602-08:22:03.090(8)?     at process._tickCallback (node.js:442:13)
```

**Comment by mpowaga** [comment]
Most likely to be the issue of `useraccounts` package. There's no `meteor-admin` in the stack trace. I'd recommend to report the issue to [useraccounts:core](https://github.com/meteor-useraccounts/core) team.
