### ISSUE TITLE
Conflict with matb33:collection-hooks?

### ISSUE THREAD

**Issue by brylie** [yogiben/meteor-admin#226]
I am getting the following error when starting a project `meteor run` that uses version 1.2.0 of this project.
```
Error: Tabular.Table options must specify collection
     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
     at packages/yogiben:admin/lib/both/startup.coffee:100:27
     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:178:2)
     at /home/brylie/Code/Apinf/api-umbrella-dashboard/.meteor/local/build/programs/server/boot.js:229:5
```

**Comment by brylie** [comment]
I have narrowed this issue down to being a potential issue with the matb33:collection-hooks package. Specifically, adding matb33:collections to a project with this package immediately causes the aforementioned error. I have opened an [issue on matb33:collection-hooks](https://github.com/matb33/meteor-collection-hooks/issues/133) for further perspective.

**Comment by brylie** [comment]
I have posted an issue describing the [load order of the 'comments' and 'collection-hooks' packages in yogiben:meteor-starter](https://github.com/yogiben/meteor-starter/issues/84) that may be the underlying cause of this issue.
