### ISSUE TITLE
Add user to role: Exception while invoking method 'adminAddUserToRole'

### ISSUE THREAD

**Issue by ArthurMaroulier** [yogiben/meteor-admin#254]
Hello, the feature to add a user to the admin role (or other role added in the roles collection) doesn't work. I've tried with a fresh install of meteor admin and meteor starter and I've got the same exception.

As far as I understand it seems to be a validation problem. If I'm correct.
See the error stack:
````
I20150805-19:39:48.335(2)? Exception while invoking method 'adminAddUserToRole' Error: When the modifier option is true, validation object must have at least one operator
I20150805-19:39:48.335(2)?     at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
I20150805-19:39:48.336(2)?     at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
I20150805-19:39:48.336(2)?     at doValidation (packages/aldeed:simple-schema/simple-schema-context.js:9:1)
I20150805-19:39:48.336(2)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed:simple-schema/simple-schema-context.js:44:1)
I20150805-19:39:48.336(2)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:317:1)
I20150805-19:39:48.336(2)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
I20150805-19:39:48.336(2)?     at Object._.extend._updateUserRoles (packages/alanning:roles/roles_common.js:680:1)
I20150805-19:39:48.336(2)?     at Object._.extend.addUsersToRoles (packages/alanning:roles/roles_common.js:145:1)
I20150805-19:39:48.337(2)?     at [object Object].Meteor.methods.adminAddUserToRole (packages/yogiben:admin/lib/server/methods.coffee:97:10)
I20150805-19:39:48.337(2)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
````

**Comment by tab00** [comment]
I've experienced the same problem.
It could be something to do with Roles.GLOBAL_GROUP and the type of roles.

Here's a quote from https://github.com/aldeed/meteor-collection2:
>   // Add `roles` to your schema if you use the meteor-roles package.
>    // Option 1: Object type
>    // If you specify that type as Object, you must also specify the
>    // `Roles.GLOBAL_GROUP` group whenever you add a user to a role.
>    // Example:
>    // Roles.addUsersToRoles(userId, ["admin"], Roles.GLOBAL_GROUP);
>    // You can't mix and match adding with and without a group since
>    // you will fail validation in some cases.
>    roles: {
>        type: Object,
>        optional: true,
>        blackbox: true
>    },
>    // Option 2: [String] type
>    // If you are sure you will never need to use role groups, then
>    // you can specify [String] as the type
>    roles: {
>        type: [String],
>        optional: true
>    }

Here is the relevant code that I've found in the compiled JavaScript:
```javascript
  adminCheckAdmin: function() {
    var adminEmails, email, user;
    check(arguments, [Match.Any]);
    user = Meteor.users.findOne({
      _id: this.userId
    });
    if (this.userId && !Roles.userIsInRole(this.userId, ['admin']) && (user.emails.length > 0)) {
      email = user.emails[0].address;
      if (typeof Meteor.settings.adminEmails !== 'undefined') {
        adminEmails = Meteor.settings.adminEmails;
        if (adminEmails.indexOf(email) > -1) {
          console.log('Adding admin user: ' + email);
          return Roles.addUsersToRoles(this.userId, ['admin'], Roles.GLOBAL_GROUP);
        }
      } else if (typeof AdminConfig !== 'undefined' && typeof AdminConfig.adminEmails === 'object') {
        adminEmails = AdminConfig.adminEmails;
        if (adminEmails.indexOf(email) > -1) {
          console.log('Adding admin user: ' + email);
          return Roles.addUsersToRoles(this.userId, ['admin'], Roles.GLOBAL_GROUP);
        }
      } else if (this.userId === Meteor.users.findOne({}, {
        sort: {
          createdAt: 1
        }
      })._id) {
        console.log('Making first user admin: ' + email);
        return Roles.addUsersToRoles(this.userId, ['admin']);
      }
    }
  },
  adminAddUserToRole: function(_id, role) {
    check(arguments, [Match.Any]);
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      return Roles.addUsersToRoles(_id, role, Roles.GLOBAL_GROUP);
    }
  },
  adminRemoveUserToRole: function(_id, role) {
    check(arguments, [Match.Any]);
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      return Roles.removeUsersFromRoles(_id, role);
    }
  },
```

Notice that in some cases Roles.GLOBAL_GROUP is a parameter whilst in others it isn't.

Please fix this as soon as possible in order to get roles working properly.

**Comment by obiwarn** [comment]
+1

**Comment by teddis** [comment]
+1

**Comment by obiwarn** [comment]
+2

**Comment by Kostanos** [comment]
I have the same issue, it is because the schema supports either roles with or without groups, but not both at the same time.
If you use roles without groups in your project, the adminAddUserToRole, adminRemoveUserToRole will rise errors, as they are hard-coded with Role.GLOBAL_GROUP - https://github.com/yogiben/meteor-admin/blob/aa33d384a202fe901703edae7fffc2fb46c24ff5/lib/server/methods.coffee#L91.

Here is my workaround:
Place it somewhere in server/ folder

```
// Overriding admin methods for roles
Meteor.startup(function () {
  Meteor.default_server.method_handlers.adminAddUserToRole = function(_id, role){
    check(_id, String);
    check(role, String);
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      Roles.addUsersToRoles(_id, role);
    }
  };
  Meteor.default_server.method_handlers.adminRemoveUserToRole = function(_id, role){
    check(_id, String);
    check(role, String);
    if (Roles.userIsInRole(this.userId, ['admin'])) {
      Roles.removeUsersFromRoles(_id, role);
    }
  }
});
```

**Comment by dpankros** [comment]
@Kostanos Your workaround worked perfectly for me.  Thanks!

**Comment by obiwarn** [comment]
@Kostanos Thanks. Works great.

**Comment by caffpain** [comment]
@Kostanos thanks!

**Comment by ideiudicibus** [comment]
thanks a lot it worked!

**Comment by kf106** [comment]
Could this be pulled into the source so it actually works from the beginning rather than requiring us to search for the problem and find this solution?
