### ISSUE TITLE
Exception while invoking method 'adminInsertDoc' ReferenceError: AdminConfig is not defined

### ISSUE THREAD

**Issue by patrickbolle** [yogiben/meteor-admin#322]
Hi folks,
loving the admin setup.

I've seen this posted a few times but with no solid answer thus far - just posting again as I am in the same situation for a business project that needs finishing.

First, meteor-admin doesn't show any of my posts in my "Listings" collection, even though there are two there.

Second, when I go to insert a listing through meteor-admin - it says Internal Server Error (500) and plasters my terminal with these errors:

I20160112-17:53:02.559(-5)? Exception while invoking method 'adminInsertDoc' ReferenceError:           AdminConfig is not defined
I20160112-17:53:02.561(-5)?     at adminCollectionObject (packages/yogiben_admin/lib/both/utils.coffee:2:5)
I20160112-17:53:02.562(-5)?     at [object Object].Meteor.methods.adminInsertDoc (packages/yogiben_admin/lib/server/methods.coffee:6:13)
I20160112-17:53:02.562(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160112-17:53:02.562(-5)?     at livedata_server.js:708:19
I20160112-17:53:02.562(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160112-17:53:02.562(-5)?     at livedata_server.js:706:40
I20160112-17:53:02.562(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160112-17:53:02.562(-5)?     at livedata_server.js:704:46
I20160112-17:53:02.562(-5)?     at tryCallTwo (/home/patrick/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160112-17:53:02.562(-5)?     at doResolve (/home/patrick/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)

My admin setup is in my client.js file as : 

    AdminConfig = {
       skin: 'blue',
       collections: {
       Listings: {}
     }
     };

Any ideas on this?
Thanks guys.

**Comment by patrickbolle** [comment]
durr.. Forgot to do the admin config in the client AND server.

Woops!
