### ISSUE TITLE
Conflicts with aldeed:collection2-core

### ISSUE THREAD

**Issue by proguru58** [yogiben/meteor-admin#388]
Hello!

I am very happy with using this package as an admin panel in my project.
In my project, I have been using aldeed:collection2-core and npm package simpl-schema since aldeed:collection2 is deprecated.

When I installed this packages in project, I got the following error message:

`W20170902-02:37:05.014(8)? (STDERR) Error: Invalid definition for pick field.
W20170902-02:37:05.015(8)? (STDERR)     at packages/aldeed_simple-schema.js:1352:13
W20170902-02:37:05.018(8)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20170902-02:37:05.019(8)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema.js:1349:5)
W20170902-02:37:05.021(8)? (STDERR)     at SubjectsCollection.c2AttachSchema [as attachSchema] (packages/aldeed_collection2.js:82:10)
W20170902-02:37:05.023(8)? (STDERR)     at meteorInstall.imports.api.subjects.subjects.js (imports/api/subjects/subjects.js:28:10)
W20170902-02:37:05.024(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170902-02:37:05.025(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170902-02:37:05.028(8)? (STDERR)     at meteorInstall.imports.startup.server.fixtures.js (imports/startup/server/fixtures.js:1:27)
W20170902-02:37:05.033(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170902-02:37:05.060(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170902-02:37:05.062(8)? (STDERR)     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:14)
W20170902-02:37:05.063(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170902-02:37:05.065(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170902-02:37:05.066(8)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:14)
W20170902-02:37:05.067(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170902-02:37:05.068(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
`
I noticed this happened by collection2 package installed as an dependency of meteor-admin.

How can I solve this problem?

Thanks

**Comment by ignacy130** [comment]
I had the similar problems without meteor-admin, I guess the meteor-admin should be updated to work with collection2-core as well as with other aldeed packages.

**Comment by BeanMc** [comment]
+1
